CREATE DATABASE "PNT";	

CREATE SCHEMA pnttest;

CREATE ROLE pnt_rw WITH ENCRYPTED PASSWORD 'kh$k982';
GRANT CONNECT ON DATABASE "PNT" TO pnt_rw;
GRANT USAGE ON SCHEMA pnttest TO pnt_rw;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA pnttest TO pnt_rw;

CREATE ROLE pnt_ro WITH ENCRYPTED PASSWORD 'd@@!r759';
GRANT CONNECT ON DATABASE "PNT" TO pnt_ro;
GRANT USAGE ON SCHEMA pnttest TO pnt_ro;
GRANT SELECT PRIVILEGES ON ALL TABLES IN SCHEMA pnttest TO pnt_ro;


CREATE TABLE pnttest.customer_info 	(
CUSTOMER_ID SERIAL NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50),
EMAIL_ID VARCHAR(100),
PASSWORD TEXT NOT NULL,
DOB DATE,
POLICY_CODE VARCHAR(8) NOT NULL
);


CREATE TABLE pnttest.genetic_result 	(
TEST_ID SERIAL NOT NULL PRIMARY KEY,
CUSTOMER_ID INT REFERENCES pnttest.customer_info (CUSTOMER_ID),
TEST_DATE TIMESTAMP NOT NULL,
GENETIC_RESULT JSON
);

CREATE INDEX idx_cust_id on pnttest.customer_info(customer_id)
